export * from './types';
export * from './registry';
export * from './animations';
export * from './invitation-fields';
export * from './invitation-layout';
export * from './components/EnvelopeReveal';
export * from './components/CenteredTextBlock';
export * from './components/ScrollLayout';
export * from './sections/HeroSection';
export * from './sections/StorySection';
export * from './sections/ScheduleSection';
export * from './sections/VenueSection';
export * from './sections/GallerySection';
export * from './sections/RsvpSection';
export * from './sections/CountdownSection';
export * from './sections/ClosingSection';

// Auto-generated template registrations
import './templates/baby-annaprashan';
import './templates/baby-birth-announcement';
import './templates/baby-cradle-ceremony';
import './templates/baby-krishna-birthday';
import './templates/baby-mundan-ceremony';
import './templates/baby-naming-ceremony';
import './templates/baby-pregnancy-announcement';
import './templates/baby-shower';
import './templates/classic_local';
import './templates/clinic-care';
import './templates/coffee-steam';
import './templates/dental-bright';
import './templates/devotional-akhand-path';
import './templates/devotional-bhagwat-katha';
import './templates/devotional-church-prayer';
import './templates/devotional-ganesh-chaturthi';
import './templates/devotional-general';
import './templates/devotional-griha-pravesh';
import './templates/devotional-khatu-shyam';
import './templates/devotional-mata-ki-chowki';
import './templates/devotional-sai-sandhya';
import './templates/devotional-satsang';
import './templates/devotional-shraddh';
import './templates/devotional-sunderkand';
import './templates/festival-bhai-dooj';
import './templates/festival-buddha-purnima';
import './templates/festival-childrens-day';
import './templates/festival-christmas';
import './templates/festival-diwali';
import './templates/festival-eid';
import './templates/festival-gurpurab';
import './templates/festival-holi';
import './templates/festival-navratri';
import './templates/festival-new-year';
import './templates/festival-rakhi';
import './templates/festival-regional-new-year';
import './templates/festival-valentines';
import './templates/gold-radiance';
import './templates/kids-birthday-jungle';
import './templates/kids-birthday-princess';
import './templates/kids-birthday-space';
import './templates/kids-birthday-superhero';
import './templates/modern_minimal';
import './templates/paper-diorama';
import './templates/party-anniversary';
import './templates/party-bbq';
import './templates/party-cocktail';
import './templates/party-dinner-elegant';
import './templates/party-farewell';
import './templates/party-grand-opening';
import './templates/party-housewarming';
import './templates/party-kitty';
import './templates/party-new-year';
import './templates/party-pool';
import './templates/party-retirement';
import './templates/party-reunion';
import './templates/receipt_style';
import './templates/restaurant_elegant';
import './templates/rope_knot';
import './templates/salon-snip';
import './templates/shutter-moment';
import './templates/silver-elegance';
import './templates/wedding-beach-destination';
import './templates/wedding-bengali';
import './templates/wedding-christian';
import './templates/wedding-engagement-ring';
import './templates/wedding-floral-romantic';
import './templates/wedding-hindu-mandap';
import './templates/wedding-modern-minimal';
import './templates/wedding-muslim-nikah';
import './templates/wedding-punjabi-bhangra';
import './templates/wedding-rajasthani-royal';
import './templates/wedding-save-the-date';
import './templates/wedding-sikh-anand-karaj';
import './templates/wedding-south-indian';
import './templates/wood_grain';
